### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by VictorMTP** [NCAR/VAPOR-SupportPage#14] opened 2019-11-22 00:36 UTC
Hi there,
   I created a netcdf file with the CF Conventions. This is simply a potential temperature at a region with lev,lat and lon as variables.
 I opened in the VAPOR interface and it worked ok up to a certain point, the Z coordinate didn't work ok. It couldn't be rendered in the Z coordinate in the Geometry section. 
My first question is: Do you know why this happens? Any idea please let me know.

Then using cfvdccreate and cf2vdc I made the vdc file. After some tries I didn't get any errors. However, when opening it again in VAPOR, through a volume render, I got the message:
Error performing paint event. Failed to read variable "theta" at time step(0), and refinement level (-1) and level-of-detail (-1)
Invalid varaible reference: theta
Error: DatMgr could not return valid values from GetVariableExtents()
Invalid varaible reference : theta

Do you know why I get this error? Even if I move the Fidelity I get similar messages.

Just as a reference I used cfvdccreate and cf2vdc as:
cfvdccreate [options] ncdf_file... vdc_file
and 
cdf2vdc [options] ncdf_file... vdc_file

Thanks a lot for your help.
Regards!
Vic

**Comment by shaomeng** [comment] 2019-11-22 04:40
Hello Vic, is it possible for you to share the simple netcdf file so we can try to reproduce your error?

**Comment by VictorMTP** [comment] 2019-11-22 18:28
Sure, here it is.
Thanks again.

**Comment by shaomeng** [comment] 2019-11-22 21:35
Hello Vic, did you use an email attachment or a link?

**Comment by VictorMTP** [comment] 2019-11-22 21:43
I attached in an email.
You can get it from here:

http://www.atmos.albany.edu/student/vtorres/page/theta3DEPAC_v3.nc

Thanks again.

**Comment by clyne** [comment] 2019-11-25 23:11
This has been fixed in version 3.2, which we plan to release in late December or January. The problem was that the Z coordinate is decreasing, and vapor was expecting increasing values. In 3.2 both increasing and decreasing coordinate variables are supported.

**Closed as completed by clyne** 2019-11-25 23:11 UTC
